AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template: Create ELB and Auto Scaling Group'
Parameters:
  StackName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Application Load Balancer should be deployed to

  Subnets:
    Description: Choose which subnets the Application Load Balancer should be deployed to
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup:
    Description: Select the Security Group to apply to the Application Load Balancer
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  # Create VPC: https://sookocheff.com/post/aws/how-to-create-a-vpc-using-cloudformation/
  # https://github.com/humank/20171116-cfn-lab/blob/master/infrastructure/vpc.yml
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name:
        "Fn::Sub":
          - "ALB-${StackName}"
          - StackName: !Ref AWS::StackName
      Subnets: !Ref Subnets
      SecurityGroups: 
        - !Ref SecurityGroup
        Tags: 
          - Key: Name
            Value: !Ref StackName

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name:
        "Fn::Sub":
          - "TG-${StackName}"
          - StackName: !Ref AWS::StackName
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckPath: /index.php
           
Outputs:
  StackName:
    Value:
      !Ref AWS::StackName

  ALBLoadBalancer:
    Description: A reference to the Application Load Balancer
    Value: !Ref LoadBalancer
    Export:
      Name: 
        "Fn::Sub": 
          - ${StackName}-ALBLoadBalancer
          - StackName: !Ref AWS::StackName

  LoadBalancerUrl:
    Description: The URL of the ALB
    Value: !Sub
      - http://${alburl}
      - alburl: !GetAtt LoadBalancer.DNSName
    Export:
      Name: 
        "Fn::Sub": 
          - ${StackName}-LoadBalancerUrl
          - StackName: !Ref AWS::StackName
  LoadBalancerListener:
    Description: A reference to a port 80 listener
    Value: !Ref LoadBalancerListener  
    Export:
      Name: 
        "Fn::Sub": 
          - ${StackName}-LoadBalancerListener
          - StackName: !Ref AWS::StackName
  ALBTargetGroup:
    Description: A reference to ALB TargetGroup
    Value: !Ref ALBTargetGroup
    Export:
      Name:
        "Fn::Sub":
          - ${StackName}-ALBTargetGroup
          - StackName: !Ref AWS::StackName
