source 'https://rubygems.org'
# source 'https://ruby.taobao.org/'

gem 'kitchen-digitalocean', '= 0.9.8'
gem 'kitchen-docker', '= 2.6.0'
gem 'kitchen-ec2', '= 1.3.2'
gem 'kitchen-vagrant', '= 1.2.1'

gem 'test-kitchen', '= 1.19.1'

gem 'berkshelf', '= 6.3.1'

gem 'foodcritic', '~> 4.0.0'
gem 'rubocop', '~> 0.48.1'
